### ISSUE TITLE
the website is down dude!

### ISSUE THREAD

**Issue by jnorthrup** [jackwootton/json-schema#41]

**Comment by jnorthrup** [comment]
more specifically, the server side doesn't complete

**Comment by jackwootton** [comment]
Can you provide an example JSON input? I just checked, and it's working for me. I did however reduce the number of backend servers to only the US. Previously there was a server in India, and the UK (to serve Asia, and Europe respectively). However because costs were running > $130 per month, I can to reduce to just one...in the US.

**Comment by jnorthrup** [comment]
this failed at time of posting.  can close now.

![image](https://user-images.githubusercontent.com/73514/52032711-b7a47600-2554-11e9-8393-d94d70f170e4.png)

**Comment by jnorthrup** [comment]
this looks like a fun project to get down to $5 per month on AWS free tier (that becomes $5 a month after 1 year)

**Comment by jnorthrup** [comment]
im thinking... emscripten and maybe some kotlin/gwt source-to-source can remove the serverside from the equation

**Comment by jnorthrup** [comment]
@jackwootton
